# Generated by Django 4.2.1 on 2023-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
